CREATE TABLE IF NOT EXISTS `BATCH_USER` (
    `ID` INT (11) UNSIGNED AUTO_INCREMENT,
    `username` VARCHAR (32),
    `address` VARCHAR (255),
    `gender` VARCHAR (32),
    PRIMARY KEY (`ID`) ) ENGINE = INNODB DEFAULT CHARSET = utf8;